spring.application.name=registry-discovery-service

# Eureka Default Operating Port
server.port=8761

# Disable self-registration
eureka.client.register-with-eureka=false

# Disable fetching registry for self
eureka.client.fetch-registry=false