spring.application.name=notification-service
server.port=8083

# -------------------------------------------------------------
# SPRING CLOUD CONFIG CLIENT
# -------------------------------------------------------------
# Pull configurations from Config Server on startup
spring.config.import=optional:configserver:http://localhost:8888

# -------------------------------------------------------------
# EUREKA CLIENT CONFIGURATION
# -------------------------------------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

# -------------------------------------------------------------
# KAFKA CONSUMER CONFIGURATION
# -------------------------------------------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=delivery-service-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializers (Wrapped in ErrorHandlingDeserializer to prevent consumer crashes)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# 1. Ignore the __TypeId__ header sent by the producer
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 2. Target local DTO class to deserialize JSON into
spring.kafka.consumer.properties.spring.json.value.default.type=com.notification.event.OrderPlacedEvent
# Allow Jackson to deserialize any trusted package payload into DTOs
spring.kafka.consumer.properties.spring.json.trusted.packages=*