spring.application.name=product-search-service
## Unique name for the microservice in Eureka Registry

## Port for this client instance
server.port=8081
#

## Eureka CLient
## Location of the Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

## Mongo -DB properties
# MongoDB Connection URI 
spring.data.mongodb.uri=mongodb://localhost:27017/products

# Marks config server as optional so the app starts even if Config Server is offline
spring.config.import=optional:configserver:http://localhost:8888/